### ISSUE TITLE
rewrite in not python

### ISSUE THREAD

**Issue by l1mey112** [t2vee/CitiesModCompatibilityChecker#3]
Stack-oriented programming is a [programming paradigm](https://en.wikipedia.org/wiki/Programming_paradigm) which relies on a [stack machine](https://en.wikipedia.org/wiki/Stack_machine) model for passing [parameters](https://en.wikipedia.org/wiki/Parameter_(computer_programming)). Stack-oriented languages operate on one or more [stacks](https://en.wikipedia.org/wiki/Stack_(data_structure)), each of which may serve a different purpose. Programming constructs in other programming languages need to be modified for use in a stack-oriented system.[[1]](https://en.wikipedia.org/wiki/Stack-oriented_programming#cite_note-1) Most stack-oriented languages operate in postfix or [Reverse Polish notation](https://en.wikipedia.org/wiki/Reverse_Polish_notation). Any arguments or parameters for a command are stated before that command. For example, postfix notation would be written 2, 3, multiply instead of multiply, 2, 3 (prefix or [Polish notation](https://en.wikipedia.org/wiki/Polish_notation)), or 2 multiply 3 ([infix notation](https://en.wikipedia.org/wiki/Infix_notation)). The programming languages [Forth](https://en.wikipedia.org/wiki/Forth_(programming_language)), [Factor](https://en.wikipedia.org/wiki/Factor_(programming_language)), [RPL](https://en.wikipedia.org/wiki/RPL_(programming_language)), [PostScript](https://en.wikipedia.org/wiki/PostScript), [BibTeX](https://en.wikipedia.org/wiki/BibTeX) style design language[[2]](https://en.wikipedia.org/wiki/Stack-oriented_programming#cite_note-2) and many [assembly languages](https://en.wikipedia.org/wiki/Assembly_language) fit this paradigm.

Stack-based algorithms consider [data](https://en.wikipedia.org/wiki/Data), by utilising one piece of data from atop the stack, and returning data back atop the stack. The need for stack manipulation operators, allow for the stack to manipulate data. To emphasise the effect of a statement, a comment is used showing the top of the stack before and after the statement. This is known as the stack effect diagram.

**Comment by t2vee** [comment]
bruh
